# Site settings

#google_analytics: UA-NNNNNNNN-N

header_pages:
 - index.md
 - about.md
 - ramblings.md
 - press.md

collections:
  ramblings:
    output: true
  press:
    output: true


footer: 'follow me on <a href="https://twitter.com/0xSH4RKS">twitter</a>'

style: dark # dark (default) or light
#listen_for_clients_preferred_style: true # true or false (default)

plugins:
  - jekyll-seo-tag
  - jekyll-toc
